version: "3.8"

services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedback_form
    ports:
      - "3000:3000"
    restart: always
    networks:
      - feedback_form_network

networks:
  feedback_form_network:
    driver: bridge
